download_url: https://galaxy.ansible.com/download/community-postgresql-2.3.2.tar.gz
format_version: 1.0.0
name: postgresql
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.3.2
version_url: https://galaxy.ansible.com/api/v2/collections/community/postgresql/versions/2.3.2/
